parameters:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/test_full_stack?useSSL=false
    username: root
    password: 12345678
    maximumPoolSize: 5